version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo2019
    ports:
      - '27017:27017'
    volumes:
      - /Volumes/DiscoVirtual/development_pessoal/utilizando-testes-em-javascript/part-5/api/MongoDB:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
